apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: nexus-joranbergfeld
  namespace: nexus
spec:
  config:
    enabled: false
    mountPath: /sonatype-nexus-conf
  deployment:
    annotations: {}
    terminationGracePeriodSeconds: 120
  route:
    enabled: false
    name: docker
    portName: docker
  secret:
    enabled: false
    mountPath: /etc/secret-volume
    readOnly: true
  ingress:
    annotations: {}
    enabled: false
    path: /
    tls:
      enabled: true
      secretName: nexus-tls
  service:
    annotations: {}
    enabled: false
    labels: {}
    ports:
      - name: nexus-service
        port: 80
        targetPort: 80
  statefulset:
    enabled: false
  replicaCount: 1
  deploymentStrategy:
    type: Recreate
  nexusProxyRoute:
    enabled: false
  tolerations: []
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    storageSize: 8Gi
  nexus:
    nexusPort: 8081
    dockerPort: 5003
    resources: {}
    imageName: >-
      registry.connect.redhat.com/sonatype/nexus-repository-manager@sha256:0a537bf191cc09fec0787300c7b4de7713afcb00f62774b7a4e5578be6b6ff0e
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    env:
      - name: INSTALL4J_ADD_VM_PARAMS
        value: >-
          -Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M
          -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
      - name: NEXUS_SECURITY_RANDOMPASSWORD
        value: 'false'
    securityContext: {}
    imagePullSecret: ''
    imagePullPolicy: IfNotPresent
    service:
      type: NodePort
    hostAliases: []
    podAnnotations: {}
