apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: github-builder-token
spec:
  encryptedData:
    password: AgC3ue0phTKOL9R8vECcdD++Asm6c9wlDt9RIyOvVjfhrXMJVrRtNLYUKARFCRGAOx8olLB4pUZVE0SwuGWyKhhMtk9kDo2u32XXk3n85n/CZ3emYeRI7Wg1eDAaoZxVKzGi00VQdEv1YVgH+tHz5XCcs4MaUzoCUHo1jae7CpzaiNY2I8X4RiXXL6l4uramMuga5vgdGrxOXRbmzRogNSuowmd/71MOLOPqtJEjqDn0plMpbuPV4ypnjRaBH4OVXrQA8fjOpnAC/HklVIvFV2DfHyPi2z7CFKDosZuNIaVYVroiNAc+k1VP2Y/Ka8Z0oZJuLgMOPeWC6teGlg5JnbVXH2KPG2XvESBSF8gS4wfZYIj81ET31e93a0O7if1IQ6Jk6Odu5HwAKFP7Kk/VA8z8W7weJGowCpgtARRCngAAcMVmmIn6vzLkgMtZQBNinEiPDNO1gnFzmxXWMJUcElGisU1w4QOxJsV2bpo5qrAETCvsAUwAC+Q3HaIAsMBrOXw9HL/24CEMcdNm4Xnkbli97RJrUFy14+5tRPBJBXdt32xwcQZG0jbhtrsBPhikKBRS02VlTsxPJm/Dy96/kCRcRotksthKmXl0Z1SwZwq563dy40LToOv0F5lu7IaiCj7I7f8G238pJgYagT9tPRUddU/se8KsD7cT2vp6BbjQlgwfmCMFeK74bL1qTRejbMF3x3fVf9OBZIgLQX0QapUvTglzans0iU2o1OBJfXv+GyvWEcEhqR2A
    username: AgC2Em9mV//AXuGlU8Un1qT1CKbYN/qZuoaj9UKPtLki8AcOltKhr64SC6slZX4Gi0iIphIEBvUuPZEazGEQ3wVEo2UYOhHGklhsLfBz33iCbsglAk+10x2hEoFVOnFwLIypIhSTB9tk2dwzYSpudnu56PuPFax5QIvKsbjUwsITNsaGxhPcogv7UCNiax3zaK0O/UDrC5cZJrTFh7XryYf+7+bHR0HKCpIoUXrm/4nEn3AXVm+BTEJDgxNjxiHEE2vn/ufgix2Vwf6Qqas8Ev6mE966GL1YAIDtRB1loKkMqC2gsEAbL9L2E1WK72VuaYTPU0V74h5vV/S/K9NqqffsexiLccRHMWBhWUGcjoN+f2M00A1P+2XkoGhBmBbX4R13zsqkrzGlze8k6e7o3QNxnKTrHjlBJtgcrkIZQD092ELSAcTr3+pNxnoHBcujKIu7Mu8Q7nTzlMFlLIQaW1yeUSX+CWmhw4Ypm1dLbUZxhEKoFx39WGRT39M0OwyUcieIxhCnF+XWOxeWjuIPlp603oX4vYF6ywxtMeigzzXA3KR4QhFQpXVQM+g9mO6RUnQLRQunixG5cq/EhY15p/y6V/ns+Kf8xVjAIq24HZpTYmIAEGcwuz1dhgtvB0WSkXsK3zif44fFiD5Uklhv3VRnQciE+P0c0CVbWRc4xgeHaXmcYiRX99TBNCHZjwtYxRS6Me94zuE8IPQR1RBF
  template:
    metadata:
      annotations:
        build.openshift.io/source-secret-match-uri-1: https://github.com/*
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: github-builder-token

