apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github 
    mappingMethod: claim 
    type: GitHub
    github:
      clientID: 04e5a452c0b18575a341
      clientSecret: 
        name: oauth-github-client-secret
      organizations: 
      - joranbergfeld-org