apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github 
    mappingMethod: claim 
    type: GitHub
    github:
      clientID: e50a1adc2816696e754b
      clientSecret: 
        name: oauth-github-client-secret
      organizations: 
      - joranbergfeld-org
