apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-cluster-issuer
spec:
  acme:
    privateKeySecretRef:
      name: amce-cluster-issuer-private-key
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    email: 'joranbergfeld@hotmail.com'
    solvers:
    - http01:
        ingress:
          class: nginx
